# Generated by Django 4.1.2 on 2022-10-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_order_status_alter_shippingaddress_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
