# Generated by Django 4.1.1 on 2022-10-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fio',
            field=models.CharField(default=2, max_length=200, verbose_name='ФИО'),
            preserve_default=False,
        ),
    ]
